# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RL Environment Directory
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Your go to place for finding that perfect learning environment. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rlenv.directory" # the base hostname & protocol for your site
twitter_username: pschydlo
github_username:  pschydlo

markdown: kramdown

include: ["data/envs_public.json","data/envs.json"]

repository: pschydlo/RLenv.directory
plugins:
  - "jekyll-github-metadata"